# Generated by Django 4.2.23 on 2025-06-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی')),
                ('image', models.ImageField(upload_to='categories-images/', verbose_name='تصویر دسته بندی')),
                ('status', models.CharField(choices=[('not-show', 'Not-Show'), ('published', 'Published')], default='not-show', max_length=10, verbose_name='وضعیت نمایش')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی غذاها',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='foods-images/', verbose_name='تصویر عکس')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('status', models.CharField(choices=[('not-show', 'Not-Show'), ('published', 'Published')], default='not-show', max_length=10, verbose_name='وضعیت نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='menu.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'غذاها ',
                'verbose_name_plural': 'لیست غذاها',
            },
        ),
    ]
