# Generated by Django 4.2.23 on 2025-06-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_category_status_alter_food_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('not-show', 'Not-Show'), ('published', 'Published')], default='not-show', max_length=10, verbose_name='وضعیت نمایش'),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('not-show', 'Not-Show'), ('published', 'Published')], default='not-show', max_length=10, verbose_name='وضعیت نمایش'),
        ),
    ]
