# Generated by Django 4.2.23 on 2025-06-24 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_city_remove_customuser_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joined_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2025, 6, 24, 3, 7, 15, 825727, tzinfo=datetime.timezone.utc)),
        ),
    ]
